application: bayes-filter-example
version: 2
runtime: python
api_version: 1

handlers:
- url: /
  script: /cgi-bin/home.py

- url: /index\.html
  script: /cgi-bin/home.py

- url: /register_(spam|organic)
  script: /cgi-bin/register_\1.py

- url: /is_spam
  script: /cgi-bin/is_spam.py

#- url: /stylesheets
#  static_dir: stylesheets

#- url: /(.*\.(gif|png|jpg))
#  static_files: static/\1
#  upload: static/(.*\.(gif|png|jpg))

#- url: /admin/.*
#  script: admin.py
#  login: admin

#- url: /.*
#  script: not_found.py
